[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "circ-maker"
version = "0.1.0"
description = "A program to output fully functional Logisim evo files"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
